# Generated by Django 5.0.4 on 2024-04-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_email_alter_users_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'hambal', 'verbose_name_plural': 'hambalner'},
        ),
    ]
